### ISSUE TITLE
OSError on/UploadVideo/

### ISSUE THREAD

**Issue by saicharan0312** [Parasgupta44/DeepVid#4]
finally after upload of the image it shows the error like 

unable to open file (unable to open file: name = 'c:\users\sai charan pd\deepvid-master dv\models\weight_150_300_incv3.hdf5, errno = 2, error message = 'no such file or directory, flags = 0, o_flags = 0)

can you please how to solve it

**Comment by saicharan0312** [comment]
Sry after upload the video

**Comment by Parasgupta44** [comment]
Hello, sorry for the late reply!
In my version of code, I have saved my trained model as weight_150_300_incv3.hdf5 and I am leveraging it in my model_pred.py file to predict the new video tags. 
`model.load_weights(BASE_DIR + "\DV\models\weight_150_300_Incv3.hdf5")`
So if you have saved it accordingly, the path shouldn't create an issue. Feel free to contact me if the issue still persists.

**Comment by Parasgupta44** [comment]
Closed.
